### ISSUE TITLE
Issue from bbert81 about 'MODULE date UNDEFINED'

### ISSUE THREAD

**Issue by hughperkins** [hughperkins/neural-style#1]
Per bbert81, from https://github.com/jcjohnson/neural-style/issues/44#issuecomment-155787537 :

it give me this :Successfully loaded models/nin_imagenet_conv.caffemodel

```
MODULE data UNDEFINED
warning: module 'data [type 5]' not found
/home/rob/torch/install/bin/luajit: models/train_val.prototxt.opencl.lua:4: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
[C]: in function 'insert'
models/train_val.prototxt.opencl.lua:4: in main chunk
[C]: in function 'dofile'
./loadcaffe_wrapper.lua:77: in function 'load'
neural_style.lua:66: in function 'main'
neural_style.lua:484: in main chunk
[C]: in function 'dofile'
.../rob/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670
any clues?
```

**Comment by hughperkins** [comment]
Hi @bbert81 , can you provide the first 10 lines of your train_val.prototxt.opencl.lua please?  Also, can you give hte output of the following commands:

```
git status
git remote -v
git log -n 10 --oneline
```

**Comment by bbert81** [comment]
10 lines of your train_val.prototxt.opencl.lua:

require 'nn'
require 'clnn'
-- warning: module 'data [type 5]' not found
table.insert(model, {'relu0', nn.ReLU(true)})
table.insert(model, {'cccp1', nn.SpatialConvolutionMM(96, 96, 1, 1, 1, 1, 0, 0)})
table.insert(model, {'relu1', nn.ReLU(true)})
table.insert(model, {'cccp2', nn.SpatialConvolutionMM(96, 96, 1, 1, 1, 1, 0, 0)})
table.insert(model, {'relu2', nn.ReLU(true)})
table.insert(model, {'pool0', nn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})
table.insert(model, {'conv2', nn.SpatialConvolutionMM(96, 256, 5, 5, 1, 1, 2, 2)})

git status:
Your branch is up-to-date with 'origin/master-nap'.

nothing to commit, working directory clean

git remote -v:
origin  https://github.com/hughperkins/neural-style.git (fetch)
origin  https://github.com/hughperkins/neural-style.git (push)

git log -n 10 --oneline:
8122fb9 sync from main fork, fold neural_style_openal.lua into neural_style.lua, add -seed option
e1c5830 Merge branch 'opencl'
dae2cee Merge branch 'master' of github.com:napsternxg/neural-style
d922421 Remove debug print statements
0d4f112 Update gitignore Add changes for using nin model
918db95 merged changes from main repo
43e9f16 Add comment on porting to openCL
af478d6 Added support for opencl. Still testing
c244f3a Try adding opencl support
03d1f29 Update README.md

**Comment by hughperkins** [comment]
Hi bbert81,

Ok, that's odd.  Seems to be missing line 3 I think.  On my computer there is an additional line `local model = {}`, so the first few lines look like:

```
require 'nn'
require 'clnn'
local model = {}
-- warning: module 'data [type 5]' not found
table.insert(model, {'conv1', nn.SpatialConvolutionMM(3, 96, 11, 11, 4, 4, 0, 0)})
table.insert(model, {'relu0', nn.ReLU(true)})
```

Can you add this plausibly missing line, and retry please?

**Comment by bbert81** [comment]
i had to change loadcaffe_wrapper.lua :
elseif line_num == 1 then
          fout:write("require 'nn'", '\n')
          fout:write("require 'clnn'", '\n')
          fout:write("local model = {}", '\n')
        end
but now i got this error:
/home/rob/torch/install/bin/luajit:
/home/rob/torch/install/share/lua/5.1/nn/Sequential.lua:44: bad argument #1
to 'updateOutput' (input channels and nInputPlane dont match)
stack traceback:
    [C]: in function 'updateOutput'
    /home/rob/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function
'forward'
    neural_style.lua:197: in function 'main'
    neural_style.lua:484: in main chunk
    [C]: in function 'dofile'
    .../rob/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in
main chunk
    [C]: at 0x00406670

2015-11-12 0:38 GMT+01:00 Hugh Perkins notifications@github.com:

**Comment by hughperkins** [comment]
Can you also provide your full commandline please?  I'm running for example like:

```
./runcl.sh
```

where runcl.sh is:

```
#!/bin/bash

name=$1
source settings.sh

th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -gpu 0 -output_image cl_$name.png -image_size $size -model_file models/vgg_normalised.caffemodel -num_iterations $its -save_iter $saveits -normalize_gradients -content_weight 50000 -style_weight 90000 -backend clnn -optimizer lbfgs -pooling avg -seed 123
```

and settings.sh is:

```
#!/bin/bash

#its=30000
its=50
saveits=50
size=200
```

My git status:

```
$ git status -uno
HEAD detached at 8122fb9
nothing to commit (use -u to show untracked files)
```

**Comment by bbert81** [comment]
well, now with :

th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg
-content_image examples/inputs/brad_pitt.jpg -gpu 0 -output_image cl.png
-image_size 180 -model_file models/vgg_normalised.caffemodel
-num_iterations 1000 -save_iter 50 -normalize_gradients -content_weight
50000 -style_weight 90000 -backend clnn -optimizer lbfgs -pooling avg -seed
123
it looks like it works! thx!
before i got that error trying to use nin_imagenet.caffemodel cause my gpu
has only 1G

2015-11-12 14:05 GMT+01:00 Hugh Perkins notifications@github.com:

**Comment by hughperkins** [comment]
> it looks like it works! thx!

Cool :-)

> before i got that error trying to use nin_imagenet.caffemodel cause my gpu has only 1G

Ah, ok.

**Comment by tigerneil** [comment]
Thanks @bbert81 I follow your suggestion, now it works!!! @hughperkins Thank you for your excellent job on opencl support for torch.
